--- #YAML:1.0
name:               Template-Plugin-CSS-LESSp
version:            0.02
abstract:           Filter your CSS with CSS::LESSp
author:
    - Michael Langner
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CSS::LESSp:           0.03
    Template::Plugin::Filter:  1.30
    Test::More:           0.80
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
